---
title: "PA_2014_Gradient_Boosting"
author: "Virat Joshi"
date: "4/23/2020"
output: html_document
---

# Set the working and data directories
```{r}
working_dir = "/Users/vjstark/Downloads/CSP-571/Project"
setwd(working_dir)

data_dir <- "./Data"
```

```{r}
# The models are saved in this directory.
model_path <- paste(dirname(rstudioapi::getActiveDocumentContext()$path), "models", sep = "/")
print(model_path)

# The train and test data are saved in this directory
model_data_path <- paste(dirname(rstudioapi::getActiveDocumentContext()$path), "data", sep = "/")
print(model_data_path)

```


# Load Essential Libraries
```{r}
library(corrplot)
library(ggplot2)
library(tidyr)
library(stringr)
library(dplyr)
library(data.table)
library(mice)
library(rstudioapi)    
library(naniar)
library(caret)
library(pROC)
library(ROCR)
library(precrec)

utils_path = './utils/utils.r'
model_utils_path = './utils/model_utils.r'
source(paste(utils_path))
source(paste(model_utils_path))
```


# Load the imputed hmda csv file.
```{r}
hmda_data_df_ <- fread(paste(data_dir, "/hmda_2014_pa_imputed.csv", sep=""))
hmda_data_df <- as.data.frame(hmda_data_df_)
```

# Explore the dataframe obtained above.
```{r}
head(hmda_data_df, 20)
# Ignore action values of 4 : Application withdrawn by applicant
# 6: Loan purchased by the institution and 2: Application approved but
# not accepted. 
# The remaining action types are 1: Loan originated, 3. Application denied
# by financial institution, 5. File closed for incompleteness and 7. Preapproval
# request denied by financial institution.
hmda_data_df <- hmda_data_df[hmda_data_df$action_taken != 2 & hmda_data_df$action_taken != 4 & hmda_data_df$action_taken != 6, ]
colnames(hmda_data_df)
```



# Create dataframe based on selected column list from the source dataframe.
```{r}
hmda_data_df_for_model <- hmda_data_frame_for_model(hmda_data_df)
hmda_data_df_for_model <- process_model_df_columns(hmda_data_df_for_model)

```


# Explore the dataframe with selected columns obtained above.

```{r}
head(hmda_data_df_for_model, 20)

nrow(hmda_data_df_for_model)

```

# Train/test split.
```{r}
set.seed(400)

split_dfs <- train_test_split(hmda_data_df_for_model$loan_granted, hmda_data_df_for_model)

train <- split_dfs[[1]]
test <- split_dfs[[2]]
```


```{r}
library(xgboost)

gb_form = loan_granted~applicant_race_and_ethnicity + applicant_income_000s + loan_amount_000s + preapproval + co_applicant_present + minority_population + loan_purpose + tract_to_msamd_income + applicant_sex + property_type + owner_occupancy + agency_code + rate_spread + respondent_id

model <- train(gb_form, data = train, method = "xgbTree",
  trControl = trainControl("cv", number = 5)
  )
```

```{r}
pred <- model %>% predict(test)
head(pred)
```

```{r}
accuracy = mean(pred == test$loan_granted)
print(accuracy)
```

```{r}
varImp(model)
```

```{r}

```

```{r}

```















